/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ABNewPersonViewControllerDelegate <NSObject>
-(void)newPersonViewController:(id)controller didCompleteWithNewPerson:(void*)newPerson;
@end

