/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PhoneTabViewController.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "MobilePhone-Structs.h"


__attribute__((visibility("hidden")))
@interface AddressBookController : XXUnknownSuperclass <PhoneTabViewController, ABPeoplePickerNavigationControllerDelegate> {
}
+(id)defaultPNGName;
+(id)tabBarIconName;
+(XXStruct_ndkk2A)badge;
+(int)tabBarSystemItem;
+(int)tabViewType;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person property:(int)property identifier:(int)identifier;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person;
-(void)peoplePickerNavigationControllerDidCancel:(id)peoplePickerNavigationController;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(BOOL)tabBarControllerShouldSelectViewController:(id)tabBarController;
-(void)unloadView;
-(void)didReceiveMemoryWarning;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)_updatePickerBanner:(id)banner;
-(void)_updatePickerPhoneNumber:(id)number;
-(void)dealloc;
-(id)init;
@end

