/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, AVController, NSArray;

__attribute__((visibility("hidden")))
@interface AudioDeviceController : XXUnknownSuperclass {
	id _delegate;
	AVController* _avController;
	NSDictionary* _pickedRoute;
	NSArray* _pickableRoutes;
}
-(void)_registerForAVControllerNotifications;
-(void)_pickableRoutesChanged;
-(void)_mediaServerDied;
-(BOOL)_routeIsReceiver:(id)receiver;
-(BOOL)_routeIsHandset:(id)handset;
-(BOOL)_routeIsSpeaker:(id)speaker;
-(void)_pickRoute:(id)route;
-(id)_pickableRoutes;
-(id)_pickedRoute;
-(void)pickRouteAtIndex:(unsigned)index;
-(id)routeNameAtIndex:(unsigned)index isPicked:(BOOL*)picked;
-(BOOL)audioCategoryIsTTY;
-(BOOL)receiverRouteIsPicked;
-(BOOL)speakerRouteIsPicked;
-(void)clearCachedRoutes;
-(void)restorePickedRoute;
-(BOOL)pickHandsetRoute;
-(BOOL)pickSpeakerRoute;
-(unsigned)numberOfAudioRoutes;
-(BOOL)routeOtherThanHandsetAndSpeakerIsAvailable;
-(BOOL)routeOtherThanHandsetIsAvailable;
-(BOOL)auxiliaryAudioRoutesAvailable;
-(void)setDelegate:(id)delegate;
-(void)invalidateAVController;
-(void)setAVController:(id)controller;
-(void)dealloc;
@end

