/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface CallSummaryHeaderView : XXUnknownSuperclass {
	NSMutableDictionary* _incomingCallTimesByDate;
	NSMutableDictionary* _outgoingCallTimesByDate;
	NSMutableArray* _orderedIncomingCallDateKeys;
	NSMutableArray* _orderedOutgoingCallDateKeys;
	int _totalNumberOfIncomingCalls;
	int _totalNumberOfOutgoingCalls;
	float _callDurationColumnOffset;
	float _callTimeRightJustification;
	int _shouldDrawSecondHeaderDate;
}
+(id)textColor;
+(id)bevelColor;
+(id)callFont;
+(id)headerFont;
-(BOOL)dateString:(id)string isTooLongForHeaderString:(id)headerString;
-(id)_formatTimeInterval:(int)interval;
-(BOOL)_shouldDrawSecondHeaderDate;
-(float)_callDurationColumnInsetXPoint;
-(float)_callTimeRightJustificationInsetXPoint;
-(float)_secondHeaderYPoint;
-(void)_drawOutgoingCalls;
-(void)_drawIncomingCalls;
-(void)_drawHorizontalRules;
-(void)drawRect:(CGRect)rect;
-(void)_resetRecentCallsDataStructures;
-(void)setRecentCalls:(id)calls;
-(id)firstOutgoingCallDictionary;
-(id)firstIncomingCallDictionary;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

