/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CNFRegWizardControllerDelegate <NSObject>
-(void)firstRunControllerDidFinish:(id)firstRunController finished:(BOOL)finished;
@end

