/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CommunicationDisplayViewController : XXUnknownSuperclass {
}
-(void)_postOkToRelock;
-(BOOL)_shouldRelock;
-(BOOL)isShowingLock;
-(BOOL)_springboardIsLocked;
-(BOOL)_lockWasInterrupted;
@end

