/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ConferenceManagementTable : XXUnknownSuperclass {
	unsigned _displaysPrivate : 1;
}
-(void)completeRowDeletionAnimation;
-(void)animateDeletionOfRowWithCell:(id)cell viaEdge:(int)edge;
-(void)conferenceParticipantCellEndClicked:(id)clicked;
-(void)conferenceParticipantCellPrivateClicked:(id)clicked;
-(BOOL)displaysPrivateButtons;
-(void)setDisplaysPrivateButtons:(BOOL)buttons;
-(id)initWithFrame:(CGRect)frame;
@end

