/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ConferenceParticipantNameView : XXUnknownSuperclass {
	NSString* _name;
	float _desiredWidth;
}
+(id)copyNameFont;
-(void)drawRect:(CGRect)rect;
-(float)desiredWidth;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithName:(id)name;
@end

