/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "ConferenceParticipantNameView.h"


__attribute__((visibility("hidden")))
@interface ConferenceParticipantHoldView : ConferenceParticipantNameView {
}
+(id)copyNameFont;
@end

