/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DialerViewDelegate <NSObject>
@optional
-(void)dialerView:(id)view stringWasPasted:(id)pasted;
-(void)dialerViewTextDidChange:(id)dialerViewText;
@end

