/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface DialerPhonePad : XXUnknownSuperclass {
}
+(float)heightForDialer;
+(id)dialerKeypadImagePressed;
+(id)dialerKeypadImage;
-(float)_yFudge;
-(id)_keypadImage;
-(id)_pressedImage;
-(id)initWithFrame:(CGRect)frame;
@end

