/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"
#import "DialerLCDFieldDelegate.h"

@class DialerLCDView, UIButton, DialerPhonePad;
@protocol DialerViewDelegate;

__attribute__((visibility("hidden")))
@interface DialerView : XXUnknownSuperclass <DialerLCDFieldDelegate> {
	DialerPhonePad* _phonePadView;
	DialerLCDView* _lcdView;
	UIButton* _addContactButton;
	BOOL _inCallMode;
	id<DialerViewDelegate> _delegate;
	UIButton* _deleteButton;
	UIButton* _callButton;
}
@property(retain, nonatomic) UIButton* deleteButton;
@property(retain, nonatomic) UIButton* callButton;
@property(retain, nonatomic) UIButton* addContactButton;
@property(assign, nonatomic) id<DialerViewDelegate> delegate;
@property(retain, nonatomic) DialerPhonePad* phonePadView;
@property(retain, nonatomic) DialerLCDView* lcdView;
@property(assign, nonatomic) BOOL inCallMode;
-(id)_callGlyphImage;
-(BOOL)_callButtonTitleWillFit;
-(void)dialerField:(id)field stringWasPasted:(id)pasted;
-(void)dialerLCDFieldTextDidChange:(id)dialerLCDFieldText;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

