/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol DialerLCDFieldDelegate <NSObject>
@optional
-(void)dialerField:(id)field stringWasPasted:(id)pasted;
-(void)dialerLCDFieldTextDidChange:(id)dialerLCDFieldText;
@end

