/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "UIStatusBarTinting.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILongPressGestureRecognizer, DialerLCDNameAndLabelView, UILabel, UIImageView;
@protocol DialerLCDFieldDelegate;

__attribute__((visibility("hidden")))
@interface DialerLCDView : XXUnknownSuperclass <UIStatusBarTinting> {
	UILabel* _numberLabel;
	BOOL _inCallMode;
	id<DialerLCDFieldDelegate> _delegate;
	UIImageView* _backgroundView;
	BOOL _highlighted;
	DialerLCDNameAndLabelView* _nameAndLabelView;
	UILongPressGestureRecognizer* _longPressRecognizer;
}
@property(retain, nonatomic) UILongPressGestureRecognizer* longPressRecognizer;
@property(retain, nonatomic) DialerLCDNameAndLabelView* nameAndLabelView;
@property(retain, nonatomic) UILabel* numberLabel;
@property(retain, nonatomic) UIImageView* backgroundView;
@property(assign, nonatomic) BOOL inCallMode;
@property(assign, nonatomic) BOOL highlighted;
@property(assign, nonatomic) id<DialerLCDFieldDelegate> delegate;
-(void)didMoveToWindow;
-(void)willMoveToWindow:(id)window;
-(id)_statusBarTintColor;
-(void)handleLongPress:(id)press;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)paste:(id)paste;
-(void)copy:(id)copy;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)resignFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(void)_displayCallout;
-(void)_menuDidHide:(id)_menu;
-(void)_menuWillHide:(id)_menu;
-(void)_requestMakeCutCopyPasteCalloutVisible:(BOOL)visible;
-(void)_makeCalloutVisible:(BOOL)visible;
-(void)_setHighlighted:(BOOL)highlighted;
-(id)_backgroundImage;
-(void)deleteCharacter;
-(void)setLabel:(id)label;
-(id)name;
-(void)setName:(id)name;
-(void)setText:(id)text needsFormat:(BOOL)format;
-(id)text;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(CGRect)numberLabelFrame;
-(float)frameHeight;
-(float)nameBottomMargin;
-(float)numberLabelMinimumFontSize;
-(float)numberLabelMaximumFontSize;
@end

