/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface EndCallExtrudeAnimation : XXUnknownSuperclass {
	float _startTitleAlpha;
	float _endTitleAlpha;
}
-(void)setProgress:(float)progress;
-(void)setEndTitleAlpha:(float)alpha;
-(void)setStartTitleAlpha:(float)alpha;
@end

