/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface LevelIndicator : XXUnknownSuperclass {
	float _level;
	UIView* _levelView;
}
-(void)setLevel:(float)level;
-(void)dealloc;
-(id)initWithDefaultSize;
@end

