/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PHATUISpecs : XXUnknownSuperclass {
}
+(int)favoritesRowAnimationForItemDeletion;
+(int)recentsRowAnimationForItemDeletion;
+(float)recentsCellIconVerticalOffsetFromBottomEdge;
+(float)recentsCellSpacingBetweenLabelAndIcon;
+(CGPoint)recentsCellLabelPosition;
+(float)recentsCellSpacingBetweenTitleAndCount;
+(CGPoint)recentsCellTitlePosition;
+(float)recentsCellDateFontSize;
+(float)recentsCellLabelFontSize;
+(float)recentsCellCountFontSize;
+(float)recentsCellNameFontSize;
+(float)favoritesCellLabelFontSize;
+(float)favoritesCellTitleFontSize;
@end

