/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSNumber, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface PhoneAudioController : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _mutedQueue;
	NSObject<OS_dispatch_queue>* _ttyQueue;
	NSObject<OS_dispatch_queue>* _pickableRoutesQueue;
	int _modifyingStateLock;
	NSNumber* _isMutedCached;
	NSNumber* _isTTYCached;
	NSArray* _pickableRoutesForTTY;
	NSArray* _pickableRoutesForNonTTY;
	BOOL _isRequestingMuted;
	BOOL _isRequestingTTY;
	BOOL _isRequestingPickableRoutesForTTY;
	BOOL _isRequestingPickableRoutesForNonTTY;
	unsigned long long _lastMutedRequestScheduleTime;
	unsigned long long _lastTTYRequestScheduleTime;
	unsigned long long _lastTTYPickableRoutesScheduleTime;
	unsigned long long _lastNonTTYPickableRoutesScheduleTime;
}
+(id)sharedPhoneAudioController;
-(id)pickableRoutesForNonTTY;
-(id)_pickableRoutesForNonTTYWithForceNewRequest:(BOOL)forceNewRequest;
-(id)pickableRoutesForTTY;
-(id)_pickableRoutesForTTYWithForceNewRequest:(BOOL)forceNewRequest;
-(id)pickableRoutes;
-(BOOL)setMuted:(BOOL)muted;
-(BOOL)isTTY;
-(BOOL)isMuted;
-(void)_requestUpdatedValueWithBlock:(id)block object:(id*)object isRequestingPointer:(BOOL*)pointer forceNewRequest:(BOOL)request scheduleTimePointer:(unsigned long long*)pointer5 notificationString:(id)string queue:(id)queue;
-(void)_handleCallStatusChanged;
-(void)_pickableRoutesDidChangeNotification:(id)_pickableRoutes;
-(void)_handleUplinkMuteDidChangeNotification:(id)_handleUplinkMute;
-(void)dealloc;
-(id)init;
@end

