/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "PhoneBaseViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class DialerController, RecentsViewController, VoicemailNavigationController, PhoneNavigationController, AddressBookController, UINavigationController, FavoritesViewController;

__attribute__((visibility("hidden")))
@interface PhoneTabBarController : XXUnknownSuperclass <PhoneBaseViewController> {
	PhoneNavigationController* _favoritesNavigationController;
	PhoneNavigationController* _recentsNavigationController;
	FavoritesViewController* _favoritesViewController;
	RecentsViewController* _recentsViewController;
	AddressBookController* _contactsViewController;
	DialerController* _keypadViewController;
	VoicemailNavigationController* _voicemailViewController;
}
@property(retain, nonatomic) VoicemailNavigationController* voicemailViewController;
@property(retain, nonatomic) DialerController* keypadViewController;
@property(retain, nonatomic) AddressBookController* contactsViewController;
@property(retain, nonatomic) RecentsViewController* recentsViewController;
@property(retain, nonatomic) FavoritesViewController* favoritesViewController;
@property(retain, nonatomic) UINavigationController* recentsNavigationController;
@property(retain, nonatomic) UINavigationController* favoritesNavigationController;
+(id)defaultPNGName;
+(int)statusBarStyle;
+(int)viewType;
-(void)transitionCompleted;
-(void)handleURL:(id)url;
-(void)prepareToHandleURL:(id)handleURL;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(BOOL)shouldDisableEdgeClip;
-(id)viewControllerForTabViewType:(int)tabViewType;
-(int)tabTypeForViewController:(id)viewController;
-(void)prepareToTransitionToTabBarViewController:(BOOL)tabBarViewController;
-(void)switchToTab:(int)tab;
-(int)currentTabViewType;
-(int)defaultTabViewType;
-(void)setSelectedViewController:(id)controller;
-(void)applicationDidResume;
-(void)_popCurrentNavigationControllerToRootViewControllerIfAppropriate;
-(void)showFavoritesTab:(BOOL)tab recentsTab:(BOOL)tab2 contactsTab:(BOOL)tab3 keypadTab:(BOOL)tab4 voicemailTab:(BOOL)tab5;
-(void)_badgeChanged:(id)changed;
-(void)_updateAllBadges:(BOOL)badges;
-(void)_stopListeningForBadgeChangedNotifications:(id)badgeChangedNotifications;
-(void)_startListeningForBadgeChangedNotifications:(id)badgeChangedNotifications;
-(BOOL)_reallyWantsFullScreenLayout;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end

