/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "PhoneBadgeable.h"
#import "MobilePhone-Structs.h"
#import "NSObject.h"


@protocol PhoneTabViewController <NSObject, PhoneBadgeable>
+(id)tabBarIconName;
+(id)defaultPNGName;
+(int)tabViewType;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
@optional
+(BOOL)requiresNavigationControllerContainer;
+(id)tabBarIconImageName;
+(id)tabBarIconImage;
+(int)tabBarSystemItem;
-(BOOL)tabBarControllerShouldSelectViewController:(id)tabBarController;
-(void)tabBarDidSelectViewController;
@end

