/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PhoneTabViewController.h"
#import "MobilePhone-Structs.h"


__attribute__((visibility("hidden")))
@interface PhoneViewController : XXUnknownSuperclass <PhoneTabViewController> {
}
+(BOOL)tabBarIconImageFinished:(id*)finished selectedImage:(id*)image forTabBarItemName:(id)tabBarItemName;
+(void)cacheFinishedTabBarIconImage:(id)image finishedSelectedTabBarIconImage:(id)image2 withTabBarItemName:(id)tabBarItemName;
+(id)defaultPNGName;
+(id)tabBarIconName;
+(XXStruct_ndkk2A)badge;
+(int)tabViewType;
+(void)initializeIconAndTitle:(id)title;
-(void)viewWillUnload;
-(void)savePreferences;
-(void)handleURL:(id)url;
-(void)prepareForSnapshot;
-(BOOL)shouldSnapshot;
-(id)contentView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)init;
@end

