/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PhoneContentView : XXUnknownSuperclass {
	BOOL _disableAppearanceEvents;
}
@property(assign, nonatomic) BOOL disableAppearanceEvents;
-(void)_didRemoveSubview:(id)subview;
-(void)willRemoveSubview:(id)subview;
-(void)insertSubview:(id)subview aboveSubview:(id)subview2;
-(void)insertSubview:(id)subview belowSubview:(id)subview2;
-(void)addSubview:(id)subview;
-(void)insertSubview:(id)subview atIndex:(int)index;
-(void)drawRect:(CGRect)rect;
@end

