/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "CNFRegWizardControllerDelegate.h"
#import "UITabBarControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class VideoConferenceController, PhoneContentView, InCallController, PhoneTabBarController, CNFRegWizardController;

__attribute__((visibility("hidden")))
@interface PhoneRootViewController : XXUnknownSuperclass <CNFRegWizardControllerDelegate, UITabBarControllerDelegate> {
	int _currentViewType;
	PhoneContentView* _contentView;
	PhoneTabBarController* _tabBarViewController;
	CNFRegWizardController* _faceTimeRegistrationViewController;
	InCallController* _inCallViewController;
	VideoConferenceController* _videoConferenceViewController;
	BOOL _faceTimeRegistrationViewIsShowing;
	BOOL _disableAutomaticAppearEvents;
	BOOL _inTransitionBetweenViewTypes;
	BOOL _returnToTabViewOnSuspendIfNeeded;
}
@property(readonly, assign, nonatomic) XXStruct_ndkk2A applicationBadge;
@property(readonly, assign, nonatomic) BOOL inTransitionBetweenViewTypes;
@property(assign, nonatomic) int currentViewType;
@property(assign, nonatomic) BOOL disableAutomaticAppearEvents;
@property(readonly, assign, nonatomic) VideoConferenceController* videoConferenceViewController;
@property(readonly, assign, nonatomic) InCallController* inCallViewController;
@property(readonly, assign, nonatomic) CNFRegWizardController* faceTimeRegistrationViewController;
@property(readonly, assign, nonatomic) PhoneTabBarController* tabBarViewController;
@property(readonly, assign, nonatomic) PhoneContentView* contentView;
-(void)resetCurrentViewType;
-(void)returnToTabViewForSuspendIfNeeded;
-(void)setupCrossfadeBackToDialingAppWithDelay:(double)delay;
-(void)tabBarController:(id)controller didSelectViewController:(id)controller2;
-(BOOL)tabBarController:(id)controller shouldSelectViewController:(id)controller2;
-(void)firstRunControllerDidFinish:(id)firstRunController finished:(BOOL)finished;
-(void)_destroyFirstRunController;
-(void)showFaceTimeFirstRunViewIfNeeded;
-(void)_createFaceTimeFirstRunViewIfNeeded;
-(void)transitionFromVideoConferenceViewToInCallViewAnimated:(BOOL)callViewAnimated completion:(id)completion;
-(void)transitionFromVideoConferenceViewToTabViewAnimated:(BOOL)tabViewAnimated completion:(id)completion;
-(void)transitionFromInCallViewToVideoConferenceViewAnimated:(BOOL)videoConferenceViewAnimated completion:(id)completion;
-(void)transitionFromInCallViewToTabViewAnimated:(BOOL)tabViewAnimated completion:(id)completion;
-(void)transitionFromTabViewToVideoConferenceViewAnimated:(BOOL)videoConferenceViewAnimated completion:(id)completion;
-(void)transitionFromTabViewToInCallViewAnimated:(BOOL)callViewAnimated completion:(id)completion;
-(void)transitionToView:(int)view animated:(BOOL)animated completionBlock:(id)block;
-(void)animateInUI;
-(void)initializeToVideoConferenceViewAnimated:(BOOL)videoConferenceViewAnimated completion:(id)completion;
-(void)initializeToInCallViewAnimated:(BOOL)callViewAnimated completion:(id)completion;
-(void)initializeToTabViewAnimated:(BOOL)tabViewAnimated completion:(id)completion;
-(void)hideContentViewAnimated:(BOOL)animated completionBlock:(id)block;
-(void)setContentViewHiddenPosition;
-(void)showContentViewAnimated:(BOOL)animated completionBlock:(id)block;
-(void)setContentViewNormalPosition;
-(BOOL)isContentViewLoaded;
-(void)setupContentViewFullSize;
-(void)setupContentViewSidebar;
-(void)_ensureProperPositionForContentView;
-(void)_unloadChildViewControllers;
-(void)_unloadViewsForController:(id)controller;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)_applicationSuspended:(id)suspended;
-(void)applicationDidResume;
-(void)_getRotationContentSettings:(XXStruct_3uUjXA*)settings;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)updateChildViewControllersForCurrentOrientation;
-(void)dealloc;
-(void)viewDidUnload;
-(void)loadView;
-(id)init;
-(BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
@end

