/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "ABPersonViewControllerDelegate.h"
#import "ABUnknownPersonViewControllerDelegate.h"
#import "MobilePhone-Structs.h"
#import "PhoneViewController.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class NSArray, ToggleButton, UITableView, RecentCall;

__attribute__((visibility("hidden")))
@interface RecentsViewController : PhoneViewController <ABPersonViewControllerDelegate, ABUnknownPersonViewControllerDelegate, UITableViewDelegate, UITableViewDataSource> {
	UITableView* _table;
	ToggleButton* _toggleButton;
	int _tableFilterMode;
	RecentCall* _call;
	unsigned _isRegisteredForActiveNotifications : 1;
	NSArray* indexPathsForMissedCalls;
	NSArray* indexPathsForNormalCalls;
}
@property(readonly, assign) NSArray* indexPathsForNormalCalls;
@property(readonly, assign) NSArray* indexPathsForMissedCalls;
@property(assign) int _tableFilterMode;
+(XXStruct_ndkk2A)badge;
+(id)tabBarIconName;
+(id)tabBarIconImageName;
+(id)tabBarIconImage;
+(int)tabViewType;
+(BOOL)requiresNavigationControllerContainer;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)_clearButtonTapped:(id)tapped;
-(void)unknownPersonViewController:(id)controller didResolveToPerson:(void*)person;
-(BOOL)personViewController:(id)controller shouldPerformDefaultActionForPerson:(void*)person property:(int)property identifier:(int)identifier;
-(void)_phoneApplicationDidChangeTabBarSelectionNotification:(id)_phoneApplication;
-(void)_applicationSuspendedNotification:(id)notification;
-(void)_applicationResumedNotification:(id)notification;
-(void)_recentsManagerCallDeletedNotification:(id)notification;
-(void)_recentsManagerSignificantChangeNotification:(id)notification;
-(void)_significantTimeChangeNotification:(id)notification;
-(void)_reloadTableViewAndNavigationBar;
-(void)_handlePhotosEverywhereChangedNotification;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)accessoryButtonTapped:(id)tapped withEvent:(id)event;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)callAtTableViewIndex:(int)tableViewIndex;
-(int)rowCountForCurrentTableMode;
-(void)resetCachedIndexes;
-(void)unloadView;
-(void)didReceiveMemoryWarning;
-(void)savePreferences;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_markAllCallsRead;
-(void)_updateNavBarButtons;
-(BOOL)shouldSnapshot;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)loadView;
-(void)showCallDetail:(id)detail animate:(BOOL)animate;
-(void)_filterWasToggled:(id)toggled;
-(void)dealloc;
-(id)init;
-(id)table;
@end

