/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class RecentsTableViewCell, NSString;

__attribute__((visibility("hidden")))
@interface RecentsTableViewCellContentView : XXUnknownSuperclass {
	RecentsTableViewCell* parentCell;
	NSString* callerName;
	NSString* callerLabel;
	NSString* countString;
	BOOL highlighted;
}
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(copy, nonatomic) NSString* countString;
@property(copy, nonatomic) NSString* callerLabel;
@property(copy, nonatomic) NSString* callerName;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame parentCell:(id)cell;
@end

