/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSDate, RecentsTableViewCellContentView, NSString, UIDateLabel, RecentCall, ABPersonIconImageView;

__attribute__((visibility("hidden")))
@interface RecentsTableViewCell : XXUnknownSuperclass {
	RecentsTableViewCellContentView* mainContentView;
	UIDateLabel* dateLabel;
	int callCategory;
	int callType;
	ABPersonIconImageView* _iconImageView;
	RecentCall* _call;
}
@property(retain) RecentCall* call;
@property(assign) int callType;
@property(assign) int callCategory;
@property(copy) NSString* callerLabel;
@property(copy) NSString* callerName;
@property(retain) NSDate* date;
+(id)_sharedRecentVideoSelectedCallImage;
+(id)_sharedRecentVideoCallImage;
+(id)_sharedOutgoingSelectedVideoImage;
+(id)_sharedOutgoingVideoImage;
+(id)_sharedOutgoingSelectedCallImage;
+(id)_sharedOutgoingCallImage;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)_setSubviewsHighlighted:(BOOL)highlighted;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(void)setIconImageFromPerson:(void*)person;
-(void)setCount:(int)count;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

