/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"


__attribute__((visibility("hidden")))
@interface SixSquareButton : XXUnknownSuperclass {
	UIEdgeInsets _contentInsets;
}
-(void)layoutSubviews;
-(void)setContentRect:(CGRect)rect;
-(void)setEnabled:(BOOL)enabled;
-(void)adjustAlpha;
-(CGRect)imageRectForContentRect:(CGRect)contentRect;
-(CGRect)titleRectForContentRect:(CGRect)contentRect;
-(id)initWithFrame:(CGRect)frame;
@end

