/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class UIImage, SixSquareButton;

__attribute__((visibility("hidden")))
@interface SixSquareView : XXUnknownSuperclass {
	SixSquareButton* _buttons[6];
	UIImage* _SixSquareButtons[6][2];
	CGSize _SixSquareTotalSize;
	id _delegate;
}
-(void)setAllButtonsEnabled:(BOOL)enabled;
-(id)buttonAtPosition:(int)position;
-(void)_cancelButtonDown:(id)down;
-(void)_buttonDown:(id)down;
-(void)_buttonHeldDownShort:(id)aShort;
-(void)_buttonHeldDown:(id)down;
-(void)_buttonClicked:(id)clicked;
-(void)setTitle:(id)title image:(id)image forPosition:(int)position;
-(void)setDelegate:(id)delegate;
-(void)removeFromSuperview;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

