/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class UILabel, UIImageView, ABPersonIconImageView;

__attribute__((visibility("hidden")))
@interface SpeedDialCell : XXUnknownSuperclass {
	UILabel* _titleTextLabel;
	UILabel* _labelTextLabel;
	UIImageView* _videoGlyphView;
	ABPersonIconImageView* _iconImageView;
	int _favoriteType;
}
@property(readonly, assign) UIImageView* videoGlyphView;
@property(assign) int favoriteType;
+(id)videoGlyphPress;
+(id)videoGlyph;
+(id)identifier;
+(id)defaultBackgroundColor;
-(BOOL)_drawsTopSeparatorDuringReordering;
-(void)_setReordering:(BOOL)reordering;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)_setSubviewsHighlighted:(BOOL)highlighted;
-(void)_updateText:(BOOL)text;
-(void)_updateImage:(BOOL)image;
-(void)setIconImageFromPerson:(void*)person;
-(void)setDisplayName:(id)name;
-(void)setLabel:(id)label;
-(BOOL)shouldDisplayVideoIcon;
-(void)dealloc;
-(id)init;
@end

