/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIActivityIndicatorView, VoicemailPlaybackController;

__attribute__((visibility("hidden")))
@interface VoicemailGreetingViewController : XXUnknownSuperclass {
	UIActivityIndicatorView* _progressSpinner;
	VoicemailPlaybackController* _playbackController;
	id _greetingDelegate;
	unsigned _dismissing : 1;
}
-(void)voicemailGreetingView:(id)view statusMessageChanged:(id)changed;
-(void)viewWillAppear:(BOOL)view;
-(void)voicemailGreetingViewSaveAbilityChanged:(id)changed;
-(void)voicemailGreetingViewSaveCompleted:(id)completed;
-(void)_saveButtonClicked:(id)clicked;
-(void)_cancelButtonClicked:(id)clicked;
-(void)_dismiss;
-(void)loadView;
-(void)setPrompt:(id)prompt showingProgress:(BOOL)progress;
-(void)_updateNavBarButtons;
-(void)setPlaybackController:(id)controller;
-(void)setGreetingDelegate:(id)delegate;
-(void)dealloc;
-(id)init;
@end

