/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class AudioDeviceController, NSString, NSTimer, AVController;

__attribute__((visibility("hidden")))
@interface VoicemailPlaybackController : XXUnknownSuperclass {
	void* _currentVoicemailRecord;
	NSString* _currentPlaybackPath;
	NSTimer* _progressUpdateTimer;
	NSTimer* _seekTimer;
	NSTimer* _delayedPlayTimer;
	id _delegate;
	AVController* _avController;
	AudioDeviceController* _audioDeviceController;
	int _lastSeekedToSecond;
	double _lastSeekedToDouble;
	float _preferredPlaybackRate;
	float _progressWidth;
	unsigned _currentRecordExpectedLength;
	unsigned _currentRecordLength;
	double _playableDuration;
	unsigned _finishedPlayback : 1;
	unsigned _ignoreElapsedTimeInUI : 1;
	unsigned _scrubbingWithProgressBar : 1;
	unsigned _displaying2xPlaybackRate : 1;
	unsigned _manuallyAdjustingPlaybackState : 1;
	unsigned _storeNeedsSave : 1;
	unsigned _finishedWhenScrubbed : 1;
	unsigned _pendingSeek : 1;
	unsigned _byeByeAV : 1;
	unsigned _didReceiveCompletionNotificationForCurrentRecord : 1;
}
@property(readonly, assign, nonatomic) AudioDeviceController* audioDeviceController;
-(void)_applicationDeactivated:(id)deactivated;
-(void)_applicationReactivated:(id)reactivated;
-(void)_enableVolumeChanges:(BOOL)changes;
-(void)voicemailControllerDied:(id)died;
-(void)voicemailPlaybackInterruptedNotification:(id)notification;
-(void)voicemailPlaybackRateChangedNotification:(id)notification;
-(void)voicemailPlaybackStateDidStopNotification:(id)voicemailPlaybackState;
-(void)voicemailPlaybackStateDidChangeItemNotification:(id)voicemailPlaybackState;
-(void)_stopTimer;
-(void)_startTimer;
-(void)_updateProgress:(id)progress;
-(void)_timeJumped:(id)jumped;
-(void)scrubberControl:(id)control didChangeToScrubValue:(float)scrubValue;
-(void)scrubberControl:(id)control didEnterScrubbingState:(BOOL)state;
-(BOOL)scrubberControlShouldBeginScrubbing:(id)scrubberControl;
-(void)seekingEnded;
-(void)_stopSeekTimer;
-(void)_updateSeekedValue;
-(void)seekingStarted;
-(void)_updateProgressUIProgress:(BOOL)progress;
-(void)updateProximitySetting;
-(void)proximityStateChanged:(id)changed;
-(BOOL)isPlayingWithDelay;
-(BOOL)isPlayingDoubleRate;
-(BOOL)isPlaying;
-(void)toggleRate;
-(void)togglePlayAllowingDelay:(BOOL)delay;
-(void)_delayedTogglePlay:(id)play;
-(void)stop;
-(void)setCurrentVoicemailRecordDataLength:(unsigned)length;
-(id)playAllowingDelay:(BOOL)delay;
-(id)playAllowingDelay:(BOOL)delay expectedLength:(unsigned)length currentLength:(unsigned)length3;
-(void)_clearDelayedPlayback;
-(id)_delayedPlay:(id)play;
-(void)setProgressWidth:(float)width;
-(void)_updateAudioCategory;
-(id)soundController;
-(BOOL)_hasVoicemailData;
-(void*)currentVoicemailRecord;
-(id)currentPlaybackPath;
-(void)setCurrentPlaybackPath:(id)path;
-(void)dataLoadCompletedNotification:(id)notification;
-(void)setCurrentVoicemailRecord:(void*)record;
-(void)_saveStoreIfNecessary;
-(void)_addItemForCurrentVoicemailRecordIfNecessary;
-(void)_updatePlayableDuration;
-(void)dealloc;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(id)initWithDeviceController:(id)deviceController;
@end

