/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDataSource.h"
#import "MobilePhone-Structs.h"

@class NSMutableDictionary, NSMutableArray, UITableView, VoicemailPlaybackController;

__attribute__((visibility("hidden")))
@interface VoicemailMailboxController : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource> {
	UITableView* table;
	NSMutableArray* recordsArray;
	BOOL showDeletedRow;
	VoicemailPlaybackController* playbackController;
	BOOL isSuspended;
	id delegate;
	BOOL isSafeToReloadData;
	int shouldAddOrRemoveDeletedRow;
	NSMutableDictionary* displayNameCache;
	NSMutableDictionary* labelsForSenderNumbersCache;
	void* lastSelectedRecord;
}
@property(readonly, assign) NSMutableArray* recordsArray;
@property(readonly, assign) void* selectedRecord;
@property(readonly, assign) UITableView* table;
@property(assign) id delegate;
@property(assign) BOOL isSuspended;
@property(assign, nonatomic) BOOL showDeletedRow;
@property(retain, nonatomic) VoicemailPlaybackController* playbackController;
-(BOOL)currentRecordIsWaitingForData;
-(void)selectAndPlayRecordWithID:(id)anId;
-(void)invalidateCachedDisplayValuesForSender:(id)sender;
-(id)numberLabelForRecord:(void*)record;
-(id)displayNameForRecord:(void*)record;
-(void)displayName:(id*)name displayLabel:(id*)label forRecord:(void*)record;
-(void)resetRecordsArray;
-(void)resume:(BOOL)resume;
-(void)suspend;
-(void)setLastSelectedRecord:(void*)record;
-(void)filterRecordsIntoRecordsArrayIfNecessary:(id)necessary;
-(void)filterRecordOutOfRecordsArrayIfNecessary:(void*)recordsArrayIfNecessary;
-(BOOL)recordBelongsInThisMailbox:(void*)thisMailbox;
-(int)rowForVoicemailRecord:(void*)voicemailRecord;
-(id)cellForVoicemailRecord:(void*)voicemailRecord;
-(void)deleteRecordAtIndexPath:(id)indexPath selectingNextViableRecord:(BOOL)record;
-(void)deleteSelectedRecord;
-(void)performMailboxDeleteActionForRecord:(void*)record;
-(void)setRecordsArray:(id)array;
-(void)refreshRecordsArray;
-(void)reloadTableDataAndSelectRecord:(void*)record;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)selectIndexPathAfterDelay:(id)delay;
-(void)setupCellAsSelected:(id)selected forRecord:(void*)record;
-(void)setupCellAsSelected:(id)selected andPlayVoicemailForRecord:(void*)record;
-(void)setupCellAsSelected:(id)selected andWaitForDataForRecord:(void*)record;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForDeleteConfirmationButtonForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didDeselectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willDeselectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)significantTimeChangeNotification:(id)notification;
-(void)voicemailTaskEndedNotification:(id)notification;
-(void)voicemailTaskStartedNotification:(id)notification;
-(void)unreadMessageCountChanged;
-(void)onlineStateChangedNotification;
-(void)localeChangedNotification:(id)notification;
-(void)handlePhotosEverywhereChangedNotification;
-(void)phoneApplicationAddressBookChangedNotification:(id)notification;
-(void)dataProgressiveLoadContinuedNotification:(id)notification;
-(void)dataProgressiveLoadStartedNotification:(id)notification;
-(void)dataLoadCompletedNotification:(id)notification;
-(void)playbackControllerStateChangedNotification:(id)notification;
-(void)voicemailStoreContentsRemovedNotification:(id)notification;
-(void)voicemailFlagsChangedNotification:(id)notification;
-(void)voicemailsAddedNotification:(id)notification;
-(void)stopListeningToAwakeNotifications;
-(void)startListeningToAwakeNotifications;
-(void)startListeningToLifetimeNotifications;
-(void)dealloc;
-(id)init;
@end

