/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIDateLabel, VoicemailCellContentView, NSString;

__attribute__((visibility("hidden")))
@interface VoicemailCell : XXUnknownSuperclass {
	VoicemailCellContentView* mainContentView;
	UIDateLabel* dateLabel;
	NSString* nameString;
	NSString* numberLabelString;
	unsigned isPlaying : 2;
	BOOL isUnread;
}
@property(assign) double date;
@property(retain) NSString* numberLabelString;
@property(retain) NSString* nameString;
+(id)_sharedUnreadIndicatorImage;
-(void)setIconImageFromPerson:(void*)person;
-(id)_automationID;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setShowsProgressIndicator:(BOOL)indicator;
-(int)playStatus;
-(BOOL)isPlaying;
-(void)setPlaying:(BOOL)playing;
-(void)_updatePlayingMarkers;
-(void)_removePlaybackMarkers;
-(BOOL)showUnreadMarker;
-(BOOL)isUnread;
-(void)setUnread:(BOOL)unread;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

