/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class UILabel, UIProgressIndicator;

__attribute__((visibility("hidden")))
@interface VoicemailSetupGreetingStatusView : XXUnknownSuperclass {
	UILabel* _textLabel;
	UIProgressIndicator* _progressIndicator;
	BOOL _showProgress;
}
-(void)setStatusString:(id)string;
-(void)setShowProgress:(BOOL)progress;
-(void)_setShowProgress:(BOOL)progress;
-(void)_adjustProgressIndicatorFrame;
-(BOOL)_shouldShowProgress;
-(BOOL)_wantsToShowProgress;
-(BOOL)_isShowingProgress;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

