/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class ABPersonIconImageView, UIProgressIndicator, UIView, VoicemailCell;

__attribute__((visibility("hidden")))
@interface VoicemailCellContentView : XXUnknownSuperclass {
	BOOL highlighted;
	UIProgressIndicator* progressIndicator;
	UIView* _playIndicator;
	UIView* _pauseIndicator;
	VoicemailCell* parentCell;
	ABPersonIconImageView* _iconImageView;
}
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setIconImageFromPerson:(void*)person;
-(void)removeProgressSpinner;
-(void)addProgressSpinner;
-(void)removePlayIndicatorIfNecessary;
-(void)removePauseIndicatorIfNecessary;
-(void)addPlayIndicator;
-(void)addPauseIndicator;
-(void)drawRect:(CGRect)rect;
-(id)_pauseIndicator;
-(id)_playIndicator;
-(id)initWithFrame:(CGRect)frame parentCell:(id)cell;
@end

