/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VoicemailReflectionButton : XXUnknownSuperclass {
	NSString* _title;
	NSString* title;
}
@property(retain) NSString* title;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)setHighlighted:(BOOL)highlighted;
-(void)layoutSubviews;
-(void)sizeToFit;
-(id)init;
-(id)initWithTitle:(id)title;
@end

