/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class VoicemailReflectionButton;

__attribute__((visibility("hidden")))
@interface VoicemailSetupPlacardCell : XXUnknownSuperclass {
	VoicemailReflectionButton* _button;
}
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)repositionTextLabel;
-(void)layoutSubviews;
-(id)button;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

