/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSString, UILabel, UIButton, UIImageView;

__attribute__((visibility("hidden")))
@interface VoicemailOutOfOrderView : XXUnknownSuperclass {
	UIImageView* _spoolImageView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIButton* _callButton;
	NSString* _carrierPhoneNumber;
}
-(void)_callCustomerService:(id)service;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

