/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class UILabel, UIProgressIndicator, UIPasscodeField, UIKeyboard, UIView;

__attribute__((visibility("hidden")))
@interface VoicemailPasscodeView : XXUnknownSuperclass {
	UIView* _top;
	UIPasscodeField* _field;
	UILabel* _prompt;
	UIKeyboard* _keyboard;
	UIProgressIndicator* _progressIndicator;
	int _maxLength;
	id _delegate;
}
-(BOOL)becomeFirstResponder;
-(BOOL)passcodeField:(id)field shouldInsertText:(id)text;
-(void)passcodeFieldTextDidChange:(id)passcodeFieldText;
-(void)setStringValue:(id)value;
-(id)stringValue;
-(void)setMaxLength:(int)length;
-(void)setEnabled:(BOOL)enabled;
-(void)setDelegate:(id)delegate;
-(void)setPrompt:(id)prompt showProgress:(BOOL)progress animate:(int)animate;
-(id)_createField;
-(id)_newPrompt;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

