/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import "VoicemailMailboxController.h"


__attribute__((visibility("hidden")))
@interface VoicemailTrashMailboxController : VoicemailMailboxController {
}
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)clearAll;
-(void)performMailboxDeleteActionForRecord:(void*)record;
-(BOOL)recordBelongsInThisMailbox:(void*)thisMailbox;
-(void)refreshRecordsArray;
-(int)_trashedCount;
@end

