/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface VoicemailOfflineView : XXUnknownSuperclass {
	UIButton* _callButton;
	UILabel* _unavailableLabel;
	UILabel* _moreWaitingLabel;
	id _delegate;
}
-(void)_callButtonClicked:(id)clicked;
-(void)setMoreWaiting:(BOOL)waiting;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
-(id)initWithWidth:(float)width dueToDisabledData:(BOOL)disabledData dueToRoaming:(BOOL)roaming;
@end

