/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"
#import "UITableViewDataSource.h"

@class UIButton;

__attribute__((visibility("hidden")))
@interface VoicemailSetupPlacard : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate> {
	UIButton* _setupButton;
	id _placardDelegate;
}
@property(assign, nonatomic) id placardDelegate;
-(void)buttonTapped:(id)tapped;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)canSelectRow:(int)row;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

