/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobilePhone-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VoicemailTaskMonitor : XXUnknownSuperclass {
	int _taskType;
	CFMachPortRef _port;
}
-(void)_taskCompleted:(id)completed;
-(void)_sendMessage:(int)message :(id)arg2;
-(void)_portInvalidated;
-(void)dealloc;
-(id)initWithTaskType:(int)taskType port:(unsigned)port;
@end

