/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (DayComparison)
-(BOOL)isSameDayAsDate:(id)date;
@end

@interface XXUnknownSuperclass (VoicemailExtras)
-(void)displayedErrorTitle:(id*)title message:(id*)message;
@end

@interface XXUnknownSuperclass (MobilePhoneAdditions)
+(id)phPathForImageNamed:(id)imageNamed inBundle:(id)bundle;
+(id)phPathForImageNamed:(id)imageNamed;
+(id)phImageNamed:(id)named;
+(id)phImageNamed:(id)named inBundle:(id)bundle;
@end

@interface XXUnknownSuperclass (Testing)
+(int)tabViewType;
-(void)transitionCompleted;
-(void)_finishSwitchTest;
-(BOOL)runTest:(id)test options:(id)options;
-(void)willStartTest:(id)test;
@end

@interface XXUnknownSuperclass (PHATUI)
+(id)PHATUIColorTextShadowOnTranslucentBlackUI;
+(id)PHATUIColorMissedCallTextOnTranslucentBlackUI;
+(id)PHATUIColorMissedCallTextOnDefaultUI;
+(id)PHATUIColorSelectedTextOnTranslucentBlackUI;
@end

@interface XXUnknownSuperclass (MPRecentsExtensions)
-(id)asIndexPaths;
@end

@interface XXUnknownSuperclass (MPRecentsExtensions)
-(id)indexPathsForCallsOfStatus:(int)status;
@end

